FROM nginx 			# Nutzt das offizielle nginx-Image als Basis
WORKDIR /usr/share/nginx/html	# Setzt das Arbeitsverzeichnis auf den Nginx-Webordner
COPY helloworld.html .		# Kopiert die Datei in das aktuelle Verzeichnis (im Container)
EXPOSE 80			# Öffnet Port 80 für den Webzugriff