version: '3.8'

networks:
  m347-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254

services:
  db:
    image: mariadb:latest
    container_name: m347-kn04a-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kn4a-db
    networks:
      m347-net:
        ipv4_address: 172.10.5.10
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m347-kn04a-web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      m347-net:
        ipv4_address: 172.10.5.20

volumes:
  db_data:
